/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package io.github.DawidC.gradle.docker

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'io.github.DawidC.gradle.docker.greeting' plugin.
 */
class DockerGradlePluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("io.github.DawidC.gradle.docker.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
