/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package io.github.DawidC.gradle.docker

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.tasks.Exec
import org.gradle.internal.os.OperatingSystem

class DockerGradlePlugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'io.github.DawidC.gradle.docker.greeting'")
            }
        }

        project.tasks.register("getOSInfo"){
            doLast {
                if (OperatingSystem.current() == OperatingSystem.WINDOWS){
                    println('windows')
                } else {
                    println('linux')
                }
            }
        }

        project.tasks.register("checkIfDockerIsRunning", Exec){

                commandLine 'ls'


        }


    }

//    def executeCommand(String command) {
//
//        commandLine command
//
//    }
}

