/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package io.github.DawidC.gradle.docker

import org.gradle.api.Project
import org.gradle.api.Plugin


class DockerGradlePlugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'io.github.DawidC.gradle.docker.greeting'")
            }
        }

        project.tasks.register("getDockerInfo"){
            exec{
                println("getDockerInf2o")
                commandLine 'ls'
            }
        }

        project.tasks.register("testDocker"){
            exec{
                commandLine 'ls'
            }
        }


    }

//    def executeCommand(String command) {
//
//        commandLine command
//
//    }
}

